### PR TITLE
refactor: move from vue-cli to vite

### LINKED ISSUE #69: did bundle size increase going to version 4?
Hello, 

Looking at bundle phobia, the gzipped bundle size went from 1.1kB to 40.4kB betrween version 3 and 4.  Does that seem right?

https://bundlephobia.com/package/vue-waypoint

### PR DESCRIPTION
**Pull request by iamandrewluca**
> With last Vue version there is an infinite callback calling in the library

> Divided PR in 2 commits to be easier to review

- Remove `.browserslistrc` https://vitejs.dev/guide/build.html#browser-compatibility
- Adjust Eslint a little, disable unneeded rules
- Update GitHub Actions node version to 14, most libraries deprecated 12
- Update GitHub Actions to run all checks
- Fix git hooks (husky) lint-staged, add commitlint
- Migrate from Jest to Vitest
- Build library in UMD and ESM format
- Fix App.vue v-for
- Simplify IntersectionObserver mock in tests
- Unwrap component.vue to component.ts because it had only script
- Infer some types, adjust main entry exports
- Simplify `cssHelpers` computation
- Fix scoped slots
- Run once prettier/eslint fix on the entire project. Except CHANGELOG.md

ps: Maybe a hook can also be extracted e.g.
```ts
const state = useWaypoint(elementRef, observerOptions)
```
ps3: Netlify fails because it uses a old distro image that should updated and it uses node 12 also

Closes #69

image

image

### CODE REVIEW

**Comment by iamandrewluca** [comment]
@scaccogatto I think we also will need to move `vue` dependency to `devDependencies` and add it also to `peerDependencies` e.g. https://github.com/vueuse/vue-demi/blob/main/package.json

https://bundlephobia.com/package/vue-waypoint@4.2.3

**Comment by iamandrewluca** [comment]
Now we talking 😄 

image

**Comment by scaccogatto** [comment]
> Now we talking 😄
> 
> image

Amazing job, I heard about vite but I never tried it. Thanks for showing me how to correctly implement it. May I buy you a beer/coffee? 🍺 😁

**Comment by iamandrewluca** [comment]
@scaccogatto Vite is pretty cool, talking over the market 😀
That's generous of you, but there is no need for that. 🙂
I'm located in Moldova near Ukraine, which is in danger right now.
If you want you could donate to Ukrainians that are in need right now. Thanks!
https://stand-with-ukraine.pp.ua/

**Pull request merged**
